# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Gust.dev – All Things Data Science"
email: ryan@gust.dev
description: >- # this means to ignore newlines until "baseurl:"
  A collection of analyses written in Python and R
  focused of deriving valuable insights from data with minimal hand-waving.
baseurl: "" # the subpath of your site, e.g. "/blog"
# twitter_username: username
github_username: Rypo
search: true
logo: "/assets/images/icons/logo_88x88.png" # added
repository: "Rypo/rypo.github.io" # added
# Build settings
markdown: kramdown
lsi: false
excerpt_separator: "\n\n"
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: default
# Outputting
# breadcrumbs: true  # disabled by default -- added
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
words_per_minute: 200 # added

# Reading Files
include:
  - .htaccess # add
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - dev
  - README.md
  - LICENSE
  - "**/*.log"
keep_files: # add
  - .git
  - .svn
# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Ryan Gust"
  avatar : #"/assets/images/bio-photo.jpg"
  bio    : "Developer, LLM & Generative AI Aficionado, Data Science Practitioner"
  location: "Greater Minneapolis-St. Paul Area, MN" # added
  email: "MY_FIRST_NAME@MY_LAST_NAME.dev" # added
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://gust.dev"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/rygu/"
    # - label: "Twitter"
      # icon: "fab fa-fw fa-twitter-square"
      # url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Rypo"
    # - label: "Instagram"
      # icon: "fab fa-fw fa-instagram"
      # url: "https://instagram.com/"

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/rygu/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Rypo"
    # - label: "Instagram"
      # icon: "fab fa-fw fa-instagram"
      # url: "https://instagram.com/"

# Collections
collections:
# Notebooks
  python:
    output: true
    permalink: /nb/:collection/:title
  r:
    output: true
    permalink: /nb/:collection/:title

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: #true
      share: true
      related: true
      permalink: /blog/:slug
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # images -- https://jekyllrb.com/docs/static-files/#add-front-matter-to-static-files
  - scope:
      path: "assets/image"
    values:
      image: true
  # _r
  - scope:
      path: "" #"nb/r/"
      type: r
    values:
      layout: rmd
      author_profile: false
      read_time: true
      share: true
      related: true
      counterpath: /nb/python/
  # _python
  - scope:
      path: "" #"/nb/python/"
      type: python
    values:
      layout: jnb
      author_profile: false
      read_time: true
      share: true
      related: true
      counterpath: /nb/r/

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

head_scripts: